<?php

namespace Tests\Unit;
use Mockery as m;
use App\Http\Controllers\Assignment\AssignmentController;
use PHPUnit\Framework\TestCase;

class AssignmentTest extends TestCase
{
    private $assignmentController;

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->assignmentController = m::mock(AssignmentController::class);
    }

    public function testItBookCreate(){
        echo("Test cases start, book added in database.\n");

        echo('Book added successfully');

    }

    public function testExample()
    {
        $this->assertTrue(true);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
